benadida/helios-server

helios_auth/auth_systems/password.py
Now using user_id on session.
Using user on session issues:
Exception Type:	TypeError
Exception Value:	<User: User object> is not JSON serializable
=> Fix user object not JSON serializable

helios/templates/election_edit.html, helios/templates/election_new.html, helios/templates/new_trustee.html, helios/tests.py, helios/views.py
CSRF tokens added to following actions: creating election, editing election, adding trustee.
=> CSRF protection added to some methods

helios/migrations/0001_initial.py, helios_auth/migrations/0001_initial.py
/cc @shirlei how does this look for initial migrations?
=> Initial migrations

helios/migrations/0001_initial.py, helios_auth/migrations/0001_initial.py
=> fixed migrations

helios/media/static_templates/question.html, helios/models.py, helios/templates/election_build.html, helios/templates/election_questions.html, helios/tests.py, helios/views.py
anyone up for reviewing this, maybe @shirlei ?
=> add ability to enter a more-info URL for each election answer

helios/models.py
remove confusing characters from password generation.
=> remove confusing characters from password generation, fixes #125

helios/crypto/algs.py, helios/crypto/electionalgs.py
Changes prevent trustees from providing providing weak key parameters and to ensure that ballot elements belong to the correct group.
=> Server-side checks of key parameters and group membership of ballot elements

helios/election_urls.py, helios/fields.py, helios/forms.py, helios/templates/election_extend.html, helios/templates/election_view.html, helios/views.py, helios/widgets.py
Implemented and fixed the necessary forms to use the voting_starts_at/ends_at/extended_until settings for elections, as outlined in #134.
=> Implement voting_starts_at/ends_at/extended_until

helios/stats_views.py, helios/templates/stats_elections.html
In case there are many elections a search helps the administrator find the election that they want.
=> Added search by name on admin page

helios/stats_views.py
I'm sorry Ben, I forgot to add a file on my last request.
=> Correction of total records displayed in the navigation bar.

helios/views.py
I had a problem sending email. If I send email in the background and delete the voter, when the email is processed the user no longer exists and an error occurs. Then I send and email, register in the log and then delete the voter.
=> Sending e-mail and improving logging to excluri voter

helios/templates/elections_administered.html
To help with the administration of the elections, I am displaying the statistics of the election in the list of all the elections.
=> Show statistics in the elections you administer

helios/templates/release_result.html, helios/views.py
I have frequent problems with election administrators who question me why voters were not informed about the release of the result.
=> Ask the administrator if they should e-mail voters about releasing the

requirements.txt
Updated psycopg2 version to latest as the previous one did not work on Heroku.
Could you please check if what I did is correct? On Heroku the main page looks correct.
Sorry but I am no expert in coding, I'm just trying on my own.
=> Updated psycopg2 version to latest

heliosverifier/verify.html
If you try to verify a election and you aren't allowed, you get the following
error. This is because it is expected a JSON result and you get, for instance,
a html page to login.
VM65:1 Uncaught SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Function.HELIOS.Election.fromJSONString (helios.js:127)
at Object.success (verify.html?election_url=/helios/elections/258ca6b1-afa4-49a3-b484-c31679d2ebbe:100)
at success (jquery-1.2.2.min.js:28)
at onreadystatechange (jquery-1.2.2.min.js:27)
=> Catch non json results when verifying election

.gitignore, helios/crypto/utils.py, helios/urls.py, helios/utils.py, helios/views.py, helios_auth/security/__init__.py, heliosbooth/boothworker-single.js, reset.sh, server_ui/urls.py
This includes the following edits:
- Reduce lot of import cluttering and overlapping (mainly in helios/views.py)
- Added .idea/ folder to .gitignore for possible devs using IntelliJ IDEs
- Minor edit to worker dispatching, explicitly checking for the correct event to dispatch
- Exit from reset.sh script immediately on first error
If any of these may be accepted, while others not, I'll surely separate the pull requests.
=> Various minor changes

helios_auth/auth_systems/facebookclient/djangofb/default_app/urls.py, helios_auth/urls.py
This makes up a modular import and exposure of URLs for different enabled login methods.
=> Import and serve only enabled auth systems urls

helios/views.py
Just a minor update, but it helps a lot when uploading multiple files.
=> Order loaded voter files by date

CONTRIBUTORS.txt
=> add recent significant contributors

heliosbooth/templates/seal.html
https://github.com/benadida/helios-server/issues/247
=> Approval voting improved message

INSTALL.md
I added to the install instructions a line about RabbitMQ.  I had a lot of problems getting it processing voter files, and read through a lot of issues and messages on the google groups, and then I simply did an apt-get install rabbitmq-server and it started working.
=> Updated INSTALL.md with comment about RabbitMQ.

extract-passwords-for-email.py
move the import lines to after django.setup() to avoid the error bellow
=> Import Helios Models After Django Setup

helios/models.py, helios/templates/voters_upload.html, helios/templates/voters_upload_confirm.html, helios/views.py
https://share.getcloudapp.com/yAuyeDN2
https://share.getcloudapp.com/v1u0qb79
=> allow bulk upload of non-password users

server_ui/templates/faq.html
https://github.com/benadida/helios-server/issues/365
=> Update incorrect Scantegrity link

helios/models.py
On Python 3, all strings are unicode strings. Helios has the `unicodecsv` dependency for reading CSV files, but that package is only intended to be used in Python 2. After upgrading Helios to Python 3, that dependency can be dropped.
After dropping the dependency, this PR tweaks the code that was using it to use the built-in `csv` module.
=> Remove unicodecsv dependency

requirements.txt
This PR upgrades the Python dependencies in `requirements.txt` to their latest minor version plus the Python version on runtime. 
Changes on those packages are non-breaking so no code changes should be required.
=> Upgrading Python packages to minor versions

helios/views.py
voter.user is virtual for users of type password
=> Fix bug when removing password voter
