benadida/helios-server

helios/datatypes/__init__.py

Aliased fields are shown for voter listing ({HELIOS_HOST}/elections/<ELECTION_ID>/voters/), but not just for one voter ({HELIOS_HOST}/elections/<ELECTION_ID>/voters/<VOTER_ID>), when using alias.

Show aliased fields for one voter if using alias 

---

settings.py

After upgrading to django 1.6.10 I had to configure this setting. If I missed something, please let me know.
Thank you!

Add ALLOWED_HOSTS setting

---

helios/templates/list_trustees.html

Hey all,
I just got to use Helios for the first time during the Node.js Foundation Individual Membership Director vote. I noticed that the explanation for trustees contained unnecessarily gendered language and wanted to fix it right away, because I couldn't find any reasons why only men could be one.
Best,
Stephan

Remove gendered language from list trustees template

---

settings.py

XFrameOptionsMiddleware added to prevent clickjacking. X-Frame-Options set to default (SAMEORIGIN). Fixes #85.

Prevent clickjacking attacks

---

helios/migrations/0002_castvote_cast_ip.py
helios/models.py
helios/views.py

@benadida  As I discussed in here https://groups.google.com/forum/#!searchin/helios-voting/cast_ip/helios-voting/VDHjssMZ1e8/nnBmm34qEgAJ, we want these info for auditing purposes,  like too many votes from the same IP address when this isn't expected (or otherwise). This field is implemented in the helios fork for the institution I work for and is working fine.
If you see problems, please, let me know. Thank you!

Add cast_ip field

---

heliosbooth/js/jscrypto/random.js

**Purpose**: Addresses a bias in the Helios booth random number generator that could allow an attacker to discover how a voter voted from the public audit trail. 
1. The default group order `q` is 256 bits. To generate a random number in the range 0..q-1 for the disjunctive proof, the booth RNG currently generates 256 random bits and returns the result modulo q, which introduces a slight modulo bias. In a two candidate race the result is that the real challenge will be  larger than the simulated challenge with a _greater than_ 50% chance. 
2. Another more severe bias could manifest if the default group parameters were ever changed. Specifically if the bit length of the group order `q` is not a power of two, such as in a safe prime group, the `bit_length / 32` will generate up to 32 fewer …

Fix bias in voting booth random number generator

---

helios/migrations/0003_auto_20160507_1948.py
helios/models.py
helios/views.py

Existing short_name is checked just when adding election. A user can inadvertently use  an existing short_name when editing an election. This will make election url unusable, for instance.
@benadida I obviously didn't succeed when trying to, let's say, 'refactor' this branch to keep pull request #101 ongoing... I guess when re-writing history I shouldn't have done one push containing just the rebase   with master... I should have done it when my changes were committed, so github wouldn't think I was crazy and  closed that pull request...  Anyway, this issue remains and I think it would be nice to fix. In my institution we had problems with users editing an election and using the same short_name...

Prevent election edit from using existing shortname

---

helios/templates/election_view.html
heliosbooth/templates/question.html

Due to a way `target="_blank"` works Helios Booth is vulnerable to phishing attacks by opening malicious candidate websites. This PR prevents those type of attacks by setting noopener/noreferrer on external links with `target="_blank"`.
More info: https://mathiasbynens.github.io/rel-noopener/
Disclaimer: this technique does not works in Safari and usage of [blankshield](https://github.com/danielstjules/blankshield) should be considered.

Prevent phishing attacks by setting noopener on external links

---

helios_auth/templates/login_box.html

Displays a link without any text when AUTH_DEFAULT_AUTH_SYSTEM in config file is assigned with 'password'.

display login button in login box

---

server_ui/glue.py
server_ui/templates/email/cast_vote_body.txt
server_ui/templates/email/cast_vote_subject.txt

I think it would be nice that this automatic e-mail be a template as well as the others sent via interface to the voter. It would allow some easier customisation to the message sent.

Make cast vote email a template

---

helios/stats_views.py
helios/templates/voters_list.html

In my helios voting instance, I registered 170 users. The users registered 980 elections and
500,000 voters. It is easier for users to check the voters list if the fields are the same and in the same order as they appear in the voter file upload.

View voter list as it is in voter file upload

---

helios/views.py

Step toward future django version upgrade
Currently, the following warning is received:
RemovedInDjango19Warning: `request.REQUEST` is deprecated, use `request.GET` or `request.POST` instead.
@benadida maybe we could start small? Fixing this kind of warning trying to make future upgrade a little more smooth?

Alter request.REQUEST to request.GET

---

helios/templates/election_keygenerator.html
helios/templates/trustee_check_sk.html
helios/templates/trustee_decrypt_and_prove.html

@benadida Google Chrome now throws "Not allowed to navigate top frame to data URL:" JavaScript exception when trying to save secret key. So, for security reasons, this is not allowed anymore and maybe other browsers may soon do the same.
Some information here:
https://ourcodeworld.com/articles/read/682/what-does-the-not-allowed-to-navigate-top-frame-to-data-url-javascript-exception-means-in-google-chrome
which links to the discussion in here:
https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM%5B1-25%5D
I've tested the changes in Firerox 64.0.2, Chrome Version 71.0.3578.98 and Safari Version 12.0.3.
Instead of opening a new window, a textarea element is shown in the same window with the content.
Since I was doing such changes, I've also put a function to download …

Fix not allowed navigate top frame

---

helios/__init__.py

@benadida This import is not being used and is causing a warning in the following form (following the idea of removing such warnings to easy future django upgrade):
RemovedInDjango19Warning: "ModelXYZ" doesn't declare an explicit app_label
Apparently this happens because it tries to import models before app configuration run.

Remove unused import causing deprecation warning

---

helios/views.py

Prevent trustee enumeration by returning the same 404 error both if trustee is not found or secret does not match.
Also, return a different 404 if election isn't found (instead of redirecting to home).

Prevent trustee enumeration

---

helios/crypto/electionalgs.py
helios/crypto/utils.py

Server and client currently generate JSON from EncryptedVote in different formats. [The client](https://github.com/shirlei/helios-server/blob/37ccbdcb64ba2e61b569b30c9fc90d817d523c42/heliosbooth/js/jscrypto/helios.js#L476) generates JSON with no whitespace (e.g. `{"key":"value"}`):
whereas [the server](https://github.com/shirlei/helios-server/blob/37ccbdcb64ba2e61b569b30c9fc90d817d523c42/helios/crypto/electionalgs.py#L342-L343) generates JSON containing whitespace after every `,` and `:` (e.g. `{"key": "value"}`).
Since the EncryptedVote hash is [computed server-side](https://github.com/shirlei/helios-server/blob/37ccbdcb64ba2e61b569b30c9fc90d817d523c42/helios/views.py#L534) when storing a ballot as an AuditedBallot, the resulting hash is different from the one originally displayed to the …

EncryptedVote JSON should not contain whitespace

---

helios/models.py

Orders trustees by id to garantee access order on "freeze" method
When Helios fetches the trustees to combine the key, it causes a series of SELECTs over the database without a fixed order.
All these SELECT statements utilize only one filter parameter ("election_id = X"), attempting to retrieve data by means of "limit" and "offset" values, even though in PostgreSQL SELECTs with no ORDER BY statement do not garantee the same order for subsequent queries.
Reference:
https://www.postgresql.org/docs/9.1/queries-order.html

Create a true Python list of Trustees

---

helios/widgets.py

Hi @benadida ! I've done some tests with the branch bens-cleaned-up-py3 running locally and as voting_start/end_date where not being saved I think the changes I've made fixes the problem. With theses changes I could save those dates, edit and extend voting with no problems. So I'm doing this PR into that branch, maybe you can test and check if those changes are appropriate. 
Nice to have you back with time to work on those big updates!

Fixes split select date time widget

---

INSTALL.md

There is a whitespace missing in the command to create a virtual environment in the INSTALL instructions.

Fix typo in install guide

---

helios/tasks.py

The email that the user receives does not contain information about the election start and end, and this information exists in the email template

The election object was not provided when the email is sent

---

helios/models.py

... which is what unicodecsv.reader expects.
This reverts 35b5cdab4d2b87d024bd80b9b09b82eab7c3b4aa which causes the
tests to error out with
```
======================================================================
ERROR: test_add_voters_file (helios.tests.ElectionModelTests)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tmp/helios-server/helios/tests.py", line 80, in test_add_voters_file
vf.process()
File "/tmp/helios-server/helios/models.py", line 806, in process
voters = list(self.itervoters())
File "/tmp/helios-server/helios/models.py", line 767, in itervoters
for voter_fields in reader:
File "/usr/lib/python3.6/site-packages/unicodecsv/py3.py", line 55, in __next__
return self.reader.__next__()
File …
```

Open voter_stream in rb (binary) mode

---

helios/models.py

SQLite doesn't know `substring()` - only `substr()` works.
In MySQL, MariaDB and PostgreSQL), `substring()` and `substr()` do the same.

Use substr() instead of substring() in SQL query

---

helios/views.py

when making a copy of the election, the election email field is not copied

fix copy help_email when copying election

---

helios/election_urls.py
helios/models.py
helios/signals.py
helios/stats_urls.py
helios/templates/election_audited_ballots.html
helios/templates/election_bboard.html
helios/templates/election_new_2.html
helios/templates/email/simple_body.txt
helios/templates/email/vote_body.txt
helios/templates/voters_list.html
helios/templates/voters_manage.html
helios/urls.py
helios/view_utils.py
helios/widgets.py
helios_auth/auth_systems/ldapauth.py
helios_auth/auth_systems/password.py
helios_auth/auth_systems/twitter.py
helios_auth/templates/login_box.html
helios_auth/urls.py
helios_auth/view_utils.py
requirements.txt
server_ui/urls.py
server_ui/view_utils.py
settings.py
urls.py

Hello everyone! I'm working on upgrading the Voting System that is used in University of Campinas (Brazil), which was based on an older version of Helios  (that was still in Python 2). To avoid starting the new project with technological dependencies, we upgraded the current Helios project from Django 2 to Django 5 and Celery 4 to 5 (and also to Python 3.11, since Django 5 doesn't support Python 3.8).
All automated tests passed the changes. Beyond that, we also performed manual use-cases:
- create election
- add questions
- bulk upload voters (password)
- freeze ballot and open election
- email voters — Time to Vote
- vote on election (cast ballot)
- post an audited ballot to tracking center
- verify audited ballot
- compute encrypted tally
- compute results
- release results
- email …

Update django version

---

requirements.txt

To be able to use Python 3.13 psycopg2 has to be updated to 2.9.10

Update psycopg2 to support Python 3.13
